add newish types
wanderers-nft/opensea-stream-rs pull request #5
Opened 2022-09-18 21:31 UTC by jdilla52

This adds order_hash and maker. Order_hash is in particular useful as it allows correlating of events much like the transaction hash, in principle this should allow the recreation of opensea's order-book using this stream.

Please pull and give it a try I only did some limited testing.

Another note: I also notices their docs weren't complete, ie bid was missing order_hash in the docs but present in the steam. I pinged opensea about it but I'm not sure when they'll update. Should probably add some sort of job to pull and build latest schema so we know when to update.

2022-09-19 00:27 UTC, the-emerald requested changes

2022-09-19 00:27 UTC, the-emerald commented on Cargo.toml
> +version = "0.3.1"
Please bump this to `0.4.0` as structs have had their public fields updated.

2022-09-19 00:27 UTC, the-emerald commented on src/schema.rs
> +    /// Creator of the listing.
Is the `maker` of `item_received_offer` the one who created the offer, or the original listing's creator? The docs are totally unclear about this - have you tested this yourself?

2022-09-19 00:27 UTC, the-emerald commented
Also, please squash all your fixup commits into one commit (force push is ok here).

2022-09-19 15:04 UTC, jdilla52 commented on src/schema.rs
> +    /// Creator of the listing.
It's the offer creator. I'll revert.

2022-09-20 00:01 UTC, jdilla52 commented
lmk if you have other standards or tests you run.

I again reached out to opensea again and mentioned the inconsistencies as well as if they would update the docs. They pinged a couple more folks on the thread I'll let you know if they get back.

2022-09-20 10:50 UTC, the-emerald commented
It all looks good! I'm just going to double check on our own end whether `item_received_bid does indeed have a `order_hash` field.

2022-09-21 09:42 UTC, the-emerald approved these changes

2022-09-21 09:54 UTC, the-emerald commented
I've moved this PR from `master` to `v0.4` because I just noticed that a new event is being served by OS as well - the `collection_offer`.

2022-09-21 09:54 UTC, merged